# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caa64c61bc56e716504c144085a24012f3e7f4e824ae8bb7546a249ab6c56f8e00225b35d6776cbd1303309936985f6e85899413c7ca65b76c4ee875a7af82e2

test:
  secret_key_base: 43f650d82e3e85258f8c0906e17ddef3f12947b9e44a8c2201367a31c4e1842e0675ef94062faac0846953c84c391e716af092fd6f59645d37ba25f02d62c421

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
